#ifdef _DEBUG
#pragma comment (lib, "opencv_calib3d440d.lib")
#pragma comment (lib, "opencv_core440d.lib")
#pragma comment (lib, "opencv_dnn440d.lib")
#pragma comment (lib, "opencv_features2d440d.lib")
#pragma comment (lib, "opencv_flann440d.lib")
#pragma comment (lib, "opencv_gapi440d.lib")
#pragma comment (lib, "opencv_highgui440d.lib")
#pragma comment (lib, "opencv_imgcodecs440d.lib")
#pragma comment (lib, "opencv_imgproc440d.lib")
#pragma comment (lib, "opencv_ml440d.lib")
#pragma comment (lib, "opencv_objdetect440d.lib")
#pragma comment (lib, "opencv_photo440d.lib")
#pragma comment (lib, "opencv_stitching440d.lib")
#pragma comment (lib, "opencv_video440d.lib")
#pragma comment (lib, "opencv_videoio440d.lib")
#else
#pragma comment (lib, "opencv_calib3d440.lib")
#pragma comment (lib, "opencv_core440.lib")
#pragma comment (lib, "opencv_dnn440.lib")
#pragma comment (lib, "opencv_features2d440.lib")
#pragma comment (lib, "opencv_flann440.lib")
#pragma comment (lib, "opencv_gapi440.lib")
#pragma comment (lib, "opencv_highgui440.lib")
#pragma comment (lib, "opencv_imgcodecs440.lib")
#pragma comment (lib, "opencv_imgproc440.lib")
#pragma comment (lib, "opencv_ml440.lib")
#pragma comment (lib, "opencv_objdetect440.lib")
#pragma comment (lib, "opencv_photo440.lib")
#pragma comment (lib, "opencv_stitching440.lib")
#pragma comment (lib, "opencv_video440.lib")
#pragma comment (lib, "opencv_videoio440.lib")
#endif